#!/usr/bin/env python3
# Sort the output of "du -h"

import sys

mult = {
    'G': 1024*1024*1024,
    'M': 1024*1024,
    'K': 1024,
}

def parse(sz):
    return float(sz[:-1]) * mult.get(sz[-1], 1)

lines = []
for line in sys.stdin:
    line = line.strip()
    toks = line.split(None, 1)
    lines.append((parse(toks[0]), line))

lines = sorted(lines, key=lambda x: x[0])
for line in lines:
    print(line[1])
